# Generated by Django 3.0.8 on 2020-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200915_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
